server:
  port: 8088
spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  datasource:
    url: jdbc:h2:mem:sb
    driver-class-name: org.h2.Driver
    username: nani
    password: nani@123
